trippywords/trippy-website

public/assets/css/main.css, resources/views/home.blade.php, resources/views/layouts/app.blade.php, resources/views/partials/footer.blade.php
Changelog:
1) Remove the dummy text is the Log In Form / Sign Up Form and free to modify this to make it look better.
2) Subscribe button needs to be resized based on the form height
3) Login and SignUp on hover should turn blue and could have round edges (New User)
4) Remove Powered By Cosmonaut link from the footer.
5) Remove the text which is just below "About Trippy Words" We strongly believe that 'Content is the King'. We realised that there is a need for a customised and structured platform where people can promote their quality content.
=> UI changes requested by Satya on home page

app/Http/Controllers/Admin/BlogController.php
- Genre list display for admin create blog and edit blog form
=> display genre for create and edit form for admin

app/Http/Controllers/Admin/AdminController.php, app/Http/Controllers/Admin/BlogController.php
logout redirect from admin dashboard
=> Admin genre issues

app/Blog.php, app/Genre.php, app/Http/Controllers/Admin/AdminController.php, app/Http/Controllers/HomeController.php
- Updated count for featured blogs and featured blog details
- featured Blogs for logged in user
=> Featured loggedin user

app/Blog.php
- Solved error for featured blog api (Guest user & Logged in user)
=> Updated featured blog display api

resources/views/home.blade.php
- way to remove tags from description
=> simple way to remove tags

resources/views/home.blade.php
Reverts trippywords/trippy-website#17
=> Revert "simple way to remove tags"

public/assets/css/main.css
=> ui fixes - recent blogs image size, search-box in dashboard.

app/Blog.php, app/Http/Controllers/Admin/BlogController.php, app/Http/Controllers/BlogController.php, resources/views/admin/blog/edit.blade.php, resources/views/blog/create.blade.php, resources/views/blog/edit.blade.php, resources/views/blog/view_draft.blade.php, resources/views/blog/view_published_blog.blade.php, resources/views/dashboard/profile.blade.php, resources/views/profile/edit.blade.php, routes/web.php
- edit blog form for admin panel as well as admin dashboard
=> Adding edit form changes for admin logged in

app/Genre.php
- commented unwanted function in genre model
=> deleted unwanted function in genre model

app/Blog.php, app/Genre.php
- Updated the feed page featured-blog and featured-blog-details API for fetching new genre table data
- These changes updated for guest as well as logged in user feed page
=> Feed page changes

app/Genre.php, app/Helpers.php, app/Http/Controllers/Auth/LoginController.php, app/Http/Controllers/DashboardController.php, app/Http/Controllers/DropdownController.php, app/Http/Controllers/ProfileController.php, app/ParentGenres.php, app/UserGenrePreference.php, resources/views/dashboard/preferance.blade.php, resources/views/profile/accounts.blade.php, routes/web.php
- parent preference selection from user dashboard
- child preference selection from user dashboard
- database table change "user_genre_preferences"
=> Preference changes

app/Http/Controllers/Admin/ParentGenreController.php, resources/views/admin/dashboard.blade.php
- parent genre creation bug solved
- dashboard on hovering effect bug solved
- clickable link to blog list on admin dashboard
=> solved bugs for genre creation and hovering effect

app/Helpers.php, app/Http/Controllers/Admin/AdminController.php, app/Http/Controllers/BlogController.php, app/Http/Controllers/DashboardController.php, resources/views/admin/partials/sidebar.blade.php, resources/views/blog/user_blog.blade.php, routes/web.php
- deleted old genre table
- impacted changes done as per new genre table
=> changes as per new genre tables

public/assets/css/main.css
=> Cff search

public/assets/css/main.css
=> cross button position fix.(TWS-7, TWS-8)

public/assets/css/main.css
=> account details - save button fix.

resources/views/home.blade.php
- if image is not uploaded for blog then sample image will display
=> home page for logged in user is broken - TWS3

resources/views/partials/footer.blade.php
=> footer width fixed TWS-10

public/assets/css/main.css
=> draft -> edit -> checkbox fix.

resources/views/blog/user_blog.blade.php
- social media icons on blog details page should open in new tab
=> solved social media icon issue TWS-4

resources/views/home.blade.php, resources/views/partials/footer.blade.php
- footer width alignment fixed
- featured detail blog alignment fixed
=> solved footer TWS-10 and alignment of home page TWS-12

app/Http/Controllers/Admin/ParentGenreController.php, public/admin-assets/js/custom/table-parent-genre.js, resources/views/admin/parent_genres/create.blade.php, resources/views/admin/parent_genres/index.blade.php
- parent genre placeholder for detail changed
- message for creating and updating parent genre fixed
- link for manage parent genre changed
- dropdown for "Is Published" changed
- saving state for data table of parent genre added
=> TWS-21,TWS-18,TWS-23,TWS-25 solved

resources/views/admin/parent_genres/create.blade.php, resources/views/admin/parent_genres/edit.blade.php
- first letter for parent genre name should be alphabet 
- parent genre name max length 50
- for edit as well as creating new genre(validation)
=> first letter should be character for parent genre

resources/views/admin/users/create.blade.php
- user create form label changed from name to username
=> label name changed to username

app/Http/Controllers/Admin/RecommendedBlogController.php, resources/views/admin/settings/settings.blade.php, resources/views/admin/smtp/smtp.blade.php
- General settings route changed(to handle exception)
- Parent Genre with no child genre API updated for recommended blogs
- SMTP settings tab route changed(to handle exception)
=> setting,smtp and recommended issue solved

resources/views/blog/blog_keyword.blade.php, resources/views/blog/user_blog.blade.php, resources/views/partials/header.blade.php
- solved unhandlled exceptions
=> solved TWS 50

resources/views/admin/users/edit.blade.php
- password field in edit user changed to new password
=> password field changed to new password

app/Http/Controllers/Admin/UserController.php
- Followers changed for deleting user
=> delete user issue solved

app/Http/Controllers/Admin/ChildGenreController.php, app/Http/Controllers/Admin/ParentGenreController.php
- parent genre delete button changed
- child genre delete button changed
=> delete button color changed

app/Http/Controllers/BlogController.php
- blog image variable declared for Unhandled exception
=> validation and field variable declared

resources/views/blog/create.blade.php
=> recent blogs on compose page unhandled exception

resources/views/admin/users/create.blade.php
=> validation for name field

resources/views/profile/accounts.blade.php
=> bookmark blog link error

resources/views/blog/blog_keyword.blade.php
- keywords user name commented
=> tags error solved

resources/views/admin/users/create.blade.php
- password field validation resolved
=> password field validation

app/Blog.php, app/Http/Controllers/HomeController.php
- for broken page of featured blog detail updated the featured blog detail API
=> Featured blog detail api is updated

resources/views/profile/ajax_profile_tabs.blade.php
- link changed for load more bookmarks
=> bookmark unhandeled exception

resources/views/blog/user_blog.blade.php
- for now the link for user detail page is commented
=> commented user detail page

resources/views/admin/users/show.blade.php
- show null value if data is not present for description field in user
=> show null if data is not present for description

resources/views/admin/users/create.blade.php
- Description placeholder changed to Summary for user CRUD
=> plaaceholder for user description changed

app/Http/Controllers/Admin/BlogController.php, app/Http/Controllers/BlogController.php
- image dimension validations for creating blog are removed
=> blog image dimension validations are removed

app/Http/Controllers/DashboardController.php, app/Http/Controllers/ProfileController.php, resources/views/blog/view_published_blog.blade.php, resources/views/dashboard/profile.blade.php, resources/views/profile/edit.blade.php
- recent blogs from dashboard (load more) is resolved
=> dashbord load more working

app/Blog.php
- featured blog detail API for home page updated for deleted blogs
=> featured blog detail change for deleted blogs

resources/views/blog/view_published_blog.blade.php
- load more blogs from recent blogs link changed
=> recent blog link changes

resources/views/blog/view_draft.blade.php
- unhandled exception for draft blogs solved
=> draft unhandled exception

app/Http/Controllers/Admin/UserController.php
- Solved unhandled exception for admin user
=> Solved unhandled exception for admin user

app/Http/Controllers/Admin/BlogController.php
- Removed json data for admin blog link
=> Removed json data

app/Http/Controllers/BlogController.php
- blogs deleted from profile should delete from bookmarked list(solved)
=> deleted blog should delete from bookmarks

app/Http/Controllers/Admin/DropdownController.php, app/Http/Controllers/DropdownController.php
- The deleted child genre should not be present in the dropdown list.(for edit blog form)
=> the deleted child should not be display

app/Blog.php, app/Http/Controllers/DashboardController.php, app/Http/Controllers/ProfileController.php, resources/views/dashboard/profile.blade.php
- a broken page for recent blogs (load more option) is resolved
=> load more recent blogs resolved

resources/views/profile/edit.blade.php
- load more error in profile page is resolved
=> Profile page load more error resolved

app/Http/Controllers/Admin/BlogController.php
- edit blog validation for admin panel resolved
=> edit blog validation resolved

resources/views/admin/child_genres/edit.blade.php
- edit child genre validation for admin panel is resolved
=> edit child genre validation resolved

app/Http/Controllers/Admin/ParentGenreController.php
- unhandled exception for parent genre update resolved
=> Resolved TWS-87

public/admin-assets/css/style.css
=> admin panel hamburger position fixed.

public/admin-assets/css/style.css
=> admin panel -> navbar(mobile) fixed.

resources/views/blog/user_blog.blade.php
- TWS-89
- Resolved unhandled exception for latest blogs from blog detail page
=> resolved unhandled exception of latest blogs

app/Http/Controllers/Admin/ChildGenreController.php
- Resolved unhandled exception in child genre controller
=> resolved TWS-88

app/Http/Controllers/Admin/ChildGenreController.php, resources/views/admin/child_genres/edit.blade.php
- Edit functionality for child genre is updates(validation done properly)
=> resolved child genre edit function

app/Http/Controllers/Admin/BlogController.php, app/Http/Controllers/Admin/DropdownController.php, app/ParentGenres.php
- dropDownController for compose and edit blog updated
- edit functionality for blog updated
=> blog edit functinality and dropdownController updated

app/ParentGenres.php
- getComposeGenre functionality from parentGenre model updated(TWS-34)
=> getComposeGenre functionality updated

resources/views/home.blade.php
- UI read more button for feed page fixed
=> UI button for feed page fixed

app/Http/Controllers/Admin/UserController.php
- added validation for user profile image field
=> user profile validation in adminpanel

app/Http/Controllers/Admin/BlogController.php, resources/views/admin/blog/edit.blade.php
- TWS-51 resolved
- validation issue for image field of blogs update for admin panel is resolved
=> Image validation

app/Http/Controllers/Admin/BlogController.php, app/Http/Controllers/Admin/ChildGenreController.php, resources/views/admin/blog/edit.blade.php, resources/views/admin/child_genres/edit.blade.php
- Genre image validation in edit resolved
- added no image in blogs CRUD
=> genre image validation issue resolved

app/Helpers.php
- blog count in profile (function)changed
=> count of blogs changed

app/Http/Controllers/Admin/BlogController.php, app/Http/Controllers/BlogController.php, resources/views/blog/create.blade.php
- validation for compose blog in profile page is added
- Image validation
- Blog is added properly
=> validation done

app/Http/Controllers/ProfileController.php, resources/views/profile/author_detail.blade.php, routes/web.php
- added route for author detail page
- added blade page for author detail page
=> Profile page route

app/Http/Controllers/BlogController.php, resources/views/search_result.blade.php
=> Blog search
